import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Fandom Hub",
  description: "Generated by Fandom Hub",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <div className="min-h-screen">
          <div
            aria-hidden="true"
            className="fixed inset-0 -z-10 bg-cover bg-center bg-no-repeat"
            style={{ backgroundImage: "url('/sub_bg.jpg')" }}
          />
          <header className="absolute inset-x-0 top-0 z-20">
            <nav className="flex items-center justify-between px-6 py-6">
              <div className="flex flex-wrap items-center gap-3">
                <Link
                  className="flex items-center gap-3 rounded-xl bg-white/85 px-4 py-3 text-gray-700 shadow-sm backdrop-blur-sm transition hover:bg-white"
                  href="/"
                  aria-label="Back to home"
                  title="Home"
                >
                  <Image
                    src="/hack_logo.png"
                    alt="Fandom Hub logo"
                    width={38}
                    height={38}
                    className="rounded-md object-cover"
                  />
                  <span className="text-base font-semibold text-gray-900">
                    Home
                  </span>
                </Link>
                <Link
                  className="rounded-lg bg-white/85 px-5 py-3 text-base font-medium text-gray-700 shadow-sm backdrop-blur-sm transition hover:bg-white"
                  href="/posts"
                >
                  Marketplace Posts
                </Link>
                <Link
                  className="rounded-lg bg-white/85 px-5 py-3 text-base font-medium text-gray-700 shadow-sm backdrop-blur-sm transition hover:bg-white"
                  href="/groupbuys"
                >
                  Group Buys
                </Link>
                <Link
                  className="rounded-lg bg-white/85 px-5 py-3 text-base font-medium text-gray-700 shadow-sm backdrop-blur-sm transition hover:bg-white"
                  href="/messages"
                >
                  Messages
                </Link>
              </div>
              <div className="flex items-center gap-3">
                <form action="/posts" className="flex items-center">
                  <input
                    type="search"
                    name="q"
                    placeholder="Search posts"
                    className="w-56 rounded-lg bg-white/85 px-4 py-3 text-base text-gray-700 shadow-sm backdrop-blur-sm outline-none transition placeholder:text-gray-500 focus:bg-white"
                  />
                </form>
                <Link
                  className="rounded-lg bg-white/85 px-5 py-3 text-base font-medium text-gray-700 shadow-sm backdrop-blur-sm transition hover:bg-white"
                  href="/profile"
                >
                  Profile
                </Link>
              </div>
            </nav>
          </header>
          <div className="pt-24">{children}</div>
        </div>
      </body>
    </html>
  );
}
